# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simple_scripting` gem.
# Please instead update this file by running `bin/tapioca gem simple_scripting`.


# pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:3
module SimpleScripting; end

# pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:5
module SimpleScripting::Argv
  extend ::SimpleScripting::Argv

  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:50
  def decode(*definition_and_options); end

  private

  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:280
  def check_no_remaining_arguments(arg_values); end

  # HELPERS ##############################################
  #
  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:286
  def compose_returned_commands(commands_stack); end

  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:176
  def decode_arguments!(params_definition, arg_values, auto_help, commands_stack = T.unsafe(nil)); end

  # Input params_definition for a non-nested case:
  #
  #   [{"command1"=>["arg1", {:long_help=>"This is the long help."}], "command2"=>["arg2"]}]
  #
  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:123
  def decode_command!(params_definition, arguments, auto_help, commands_stack = T.unsafe(nil)); end

  # This is trivial to define with named arguments, however, Ruby 2.6 removed the support for
  # mixing strings and symbols as argument keys, so we're forced to perform manual decoding.
  # The complexity of this code supports the rationale for the removal of the functionality.
  #
  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:96
  def decode_definition_and_options(definition_and_options); end

  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:251
  def process_argument_definition!(param_definition, args); end

  # DEFINITIONS PROCESSING ###############################
  #
  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:228
  def process_option_definition!(param_definition, parser_opts, result); end

  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:270
  def process_regular_argument!(arg_values, result, commands_stack, arg_name, arg_is_mandatory); end

  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:263
  def process_varargs!(arg_values, result, commands_stack, arg_name, arg_is_mandatory); end
end

# The fact that the following errors don't descend from OptionParser::InvalidOption is somewhat
# annoying, however, there should be no practical problem.
#
# pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:10
class SimpleScripting::Argv::ArgumentError < ::StandardError; end

# pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:30
class SimpleScripting::Argv::ExitWithArgumentsHelpPrinting < ::Struct
  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:31
  def print_help(output, long_help); end
end

# pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:23
class SimpleScripting::Argv::ExitWithCommandsHelpPrinting < ::Struct
  # Note that :long_help is not used.
  #
  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:25
  def print_help(output, long_help); end
end

# pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:12
class SimpleScripting::Argv::InvalidCommand < ::StandardError
  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:16
  def initialize(message, valid_commands); end

  # pkg:gem/simple_scripting#lib/simple_scripting/argv.rb:14
  def valid_commands; end
end
