inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.6

Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'bin/geet'                                 # Program entry point switch/case

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'                        # RSpec is styled in long blocks

Metrics/ClassLength:
  Exclude:
    - 'lib/geet/git/repository.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/geet/github/api_interface.rb'         # Switch-case (HTTP) parameter decoding
    - 'lib/geet/gitlab/api_interface.rb'         # Switch-case (HTTP) parameter decoding
    - 'bin/geet'                                 # Program entry point switch/case

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'lib/geet/git/repository.rb'               # Table-style code
    - 'lib/geet/commandline/configuration.rb'    # Table-style code

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'bin/geet'                                 # Program entry point switch/case
    - 'lib/geet/commandline/configuration.rb'    # Table-style code

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/geet/services/create_issue.rb'        # The creation method has many parameters
    - 'lib/geet/services/create_pr.rb'           # The creation method has many parameters
    - 'bin/geet'                                 # Program entry point switch/case

Style/BlockComments:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
  Enabled: true
