AllCops:
  NewCops: disable

Metrics/MethodLength:
  Enabled: false

# Offense count: 20
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, AllowedPatterns, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Enabled: false

# Offense count: 1
# Configuration parameters: Include.
# Include: **/*.gemspec
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'geet.gemspec'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Layout/ClosingParenthesisIndentation:
  Exclude:
    - 'lib/geet/services/create_issue.rb'

# Offense count: 8
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowForAlignment.
Layout/CommentIndentation:
  Exclude:
    - 'spec/integration/create_pr_spec.rb'
    - 'spec/integration/merge_pr_spec.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
Layout/ElseAlignment:
  Exclude:
    - 'lib/geet/github/pr.rb'
    - 'lib/geet/helpers/services_workflow_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'lib/geet/github/api_interface.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, no_empty_lines
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/integration/list_issues_spec.rb'
    - 'spec/integration/open_pr_spec.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleAlignWith, Severity.
# SupportedStylesAlignWith: keyword, variable, start_of_line
Layout/EndAlignment:
  Exclude:
    - 'lib/geet/github/pr.rb'
    - 'lib/geet/helpers/services_workflow_helper.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowForAlignment, AllowBeforeTrailingComments, ForceEqualSignAlignment.
Layout/ExtraSpacing:
  Exclude:
    - 'lib/geet/commandline/configuration.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: consistent, align_parentheses
Layout/FirstParameterIndentation:
  Exclude:
    - 'lib/geet/services/create_issue.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: Width, AllowedPatterns, IgnoredPatterns.
Layout/IndentationWidth:
  Exclude:
    - 'lib/geet/github/pr.rb'
    - 'lib/geet/helpers/services_workflow_helper.rb'

# Offense count: 3
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowForAlignment, EnforcedStyleForExponentOperator.
# SupportedStylesForExponentOperator: space, no_space
Layout/SpaceAroundOperators:
  Exclude:
    - 'geet.gemspec'
    - 'lib/geet/helpers/os_helper.rb'

# Offense count: 10
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces.
# SupportedStyles: space, no_space, compact
# SupportedStylesForEmptyBraces: space, no_space
Layout/SpaceInsideHashLiteralBraces:
  Exclude:
    - 'bin/geet'
    - 'lib/geet/services/open_repo.rb'
    - 'lib/geet/utils/git_client.rb'
    - 'lib/geet/utils/manual_list_selection.rb'
    - 'spec/spec_helper.rb'

# Offense count: 3
# Configuration parameters: AllowedMethods.
# AllowedMethods: enums
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/integration/open_repo_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Lint/DeprecatedClassMethods:
  Exclude:
    - 'bin/geet'

# Offense count: 1
# Configuration parameters: AllowComments.
Lint/EmptyWhen:
  Exclude:
    - 'lib/geet/services/open_repo.rb'

# Offense count: 1
# Configuration parameters: MaximumRangeSize.
Lint/MissingCopEnableDirective:
  Exclude:
    - 'lib/geet/commandline/configuration.rb'

# Offense count: 2
# This cop supports unsafe autocorrection (--autocorrect-all).
Lint/NonDeterministicRequireOrder:
  Exclude:
    - 'bin/geet'
    - 'lib/geet/git/repository.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Lint/RedundantCopDisableDirective:
  Exclude:
    - 'lib/geet/commandline/configuration.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: IgnoreEmptyBlocks, AllowUnusedKeywordArguments.
Lint/UnusedBlockArgument:
  Exclude:
    - 'lib/geet/gitlab/issue.rb'
    - 'lib/geet/gitlab/pr.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods, IgnoreNotImplementedMethods.
Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/geet/services/open_pr.rb'
    - 'lib/geet/utils/git_client.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: ContextCreatingMethods, MethodCreatingMethods.
Lint/UselessAccessModifier:
  Exclude:
    - 'lib/geet/github/milestone.rb'

# Offense count: 1
Lint/UselessAssignment:
  Exclude:
    - 'lib/geet/services/create_issue.rb'

# Offense count: 10
# Configuration parameters: AllowedMethods, AllowedPatterns, IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 65

# Offense count: 18
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, AllowedMethods, AllowedPatterns, IgnoredMethods.
# AllowedMethods: refine
Metrics/BlockLength:
  Max: 88

# Offense count: 1
# Configuration parameters: CountBlocks.
Metrics/BlockNesting:
  Max: 4

# Offense count: 4
# Configuration parameters: CountComments, CountAsOne.
Metrics/ClassLength:
  Max: 126

# Offense count: 6
# Configuration parameters: AllowedMethods, AllowedPatterns, IgnoredMethods.
Metrics/CyclomaticComplexity:
  Max: 20

# Offense count: 4
# Configuration parameters: CountKeywordArgs, MaxOptionalParameters.
Metrics/ParameterLists:
  Max: 9

# Offense count: 4
# Configuration parameters: AllowedMethods, AllowedPatterns, IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 12

# Offense count: 5
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: at, by, db, id, in, io, ip, of, on, os, pp, to
Naming/MethodParameterName:
  Exclude:
    - 'lib/geet/services/create_pr.rb'
    - 'lib/geet/services/merge_pr.rb'

# Offense count: 2
# Configuration parameters: NamePrefix, ForbiddenPrefixes, AllowedMethods, MethodDefinitionMacros.
# NamePrefix: is_, has_, have_
# ForbiddenPrefixes: is_, has_, have_
# AllowedMethods: is_a?
# MethodDefinitionMacros: define_method, define_singleton_method
Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'lib/geet/github/user.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: PreferredName.
Naming/RescuedExceptionsVariableName:
  Exclude:
    - 'lib/geet/github/user.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 34
# This cop supports unsafe autocorrection (--autocorrect-all).
Style/CommentedKeyword:
  Enabled: false

# Offense count: 38
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Enabled: false

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: allowed_in_returns, forbidden
Style/DoubleNegation:
  Exclude:
    - 'bin/geet'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, AllowComments.
# SupportedStyles: empty, nil, both
Style/EmptyElse:
  Exclude:
    - 'lib/geet/utils/git_client.rb'

# Offense count: 2
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Exclude:
    - 'Rakefile'
    - 'lib/geet/shared/http_error.rb'

# Offense count: 6
# Configuration parameters: MinBodyLength, AllowConsecutiveConditionals.
Style/GuardClause:
  Exclude:
    - 'lib/geet/git/repository.rb'
    - 'lib/geet/github/pr.rb'
    - 'lib/geet/gitlab/pr.rb'
    - 'lib/geet/utils/git_client.rb'

# Offense count: 7
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: braces, no_braces
Style/HashAsLastArrayItem:
  Exclude:
    - 'lib/geet/commandline/configuration.rb'

# Offense count: 8
# This cop supports safe autocorrection (--autocorrect).
Style/IfUnlessModifier:
  Exclude:
    - 'lib/geet/git/repository.rb'
    - 'lib/geet/github/pr.rb'
    - 'lib/geet/gitlab/pr.rb'
    - 'lib/geet/helpers/os_helper.rb'
    - 'lib/geet/services/create_issue.rb'
    - 'lib/geet/services/create_pr.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
Style/InfiniteLoop:
  Exclude:
    - 'lib/geet/services/create_pr.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: line_count_dependent, lambda, literal
Style/Lambda:
  Exclude:
    - 'spec/integration/create_pr_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: call, braces
Style/LambdaCall:
  Exclude:
    - 'lib/geet/utils/attributes_selection_manager.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowedMethods, AllowedPatterns, IgnoredMethods.
Style/MethodCallWithoutArgsParentheses:
  Exclude:
    - 'lib/geet/utils/git_client.rb'

# Offense count: 5
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: literals, strict
Style/MutableConstant:
  Exclude:
    - 'lib/geet/shared/repo_permissions.rb'
    - 'lib/geet/utils/git_client.rb'
    - 'spec/integration/open_repo_spec.rb'

# Offense count: 10
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: both, prefix, postfix
Style/NegatedIf:
  Exclude:
    - 'lib/geet/git/repository.rb'
    - 'lib/geet/github/api_interface.rb'
    - 'lib/geet/github/user.rb'
    - 'lib/geet/gitlab/api_interface.rb'
    - 'lib/geet/gitlab/pr.rb'
    - 'lib/geet/services/create_issue.rb'
    - 'lib/geet/services/create_pr.rb'
    - 'lib/geet/utils/attributes_selection_manager.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: Strict, AllowedNumbers, AllowedPatterns.
Style/NumericLiterals:
  MinDigits: 6

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'lib/geet/utils/git_client.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantFreeze:
  Exclude:
    - 'lib/geet/shared/selection.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantSelf:
  Exclude:
    - 'lib/geet/github/remote_repository.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Exclude:
    - 'lib/geet/utils/git_client.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
Style/SlicingWithRange:
  Exclude:
    - 'lib/geet/utils/git_client.rb'

# Offense count: 3
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: Mode.
Style/StringConcatenation:
  Exclude:
    - 'lib/geet/commandline/editor.rb'
    - 'lib/geet/github/api_interface.rb'
    - 'lib/geet/gitlab/api_interface.rb'

# Offense count: 22
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'lib/geet/commandline/configuration.rb'
    - 'lib/geet/git/repository.rb'
    - 'lib/geet/github/remote_repository.rb'
    - 'lib/geet/helpers/os_helper.rb'
    - 'lib/geet/helpers/summary_helper.rb'
    - 'lib/geet/services/add_upstream_repo.rb'
    - 'lib/geet/services/create_pr.rb'
    - 'lib/geet/services/merge_pr.rb'
    - 'lib/geet/utils/git_client.rb'
    - 'spec/integration/open_repo_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiteralsInInterpolation:
  Exclude:
    - 'lib/geet/utils/git_client.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, AllowSafeAssignment.
# SupportedStyles: require_parentheses, require_no_parentheses, require_parentheses_when_complex
Style/TernaryParentheses:
  Exclude:
    - 'lib/geet/github/user.rb'

# Offense count: 6
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInArrayLiteral:
  Exclude:
    - 'lib/geet/commandline/configuration.rb'
    - 'lib/geet/shared/repo_permissions.rb'

# Offense count: 8
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInHashLiteral:
  Exclude:
    - 'lib/geet/commandline/configuration.rb'
    - 'spec/integration/open_repo_spec.rb'
