inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 160

Style/DoubleNegation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false
