dist: bionic
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
# API tokens are always required, but not used in testing, since no requests are actually made.
env:
  - GITHUB_API_TOKEN=phony GITLAB_API_TOKEN=phony
