#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib/geet/helpers/configuration_helper.rb'
require_relative 'lib/geet/git/repository.rb'

if $PROGRAM_NAME == __FILE__
  include Geet

  configuration_helper = Helpers::ConfigurationHelper.new

  command, options = configuration_helper.decode_argv || exit
  api_token = configuration_helper.api_token

  title, description = options.values_at(:title, :description)

  repository = Git::Repository.new(api_token)

  case command
  when Helpers::ConfigurationHelper::ISSUE_CREATE_COMMAND
    Services::CreateIssue.new.execute(repository, title, description, options)
  when Helpers::ConfigurationHelper::ISSUE_LIST_COMMAND
    Services::ListIssues.new.execute(repository)
  when Helpers::ConfigurationHelper::PR_CREATE_COMMAND
    Services::CreatePr.new.execute(repository, title, description, options)
  else
    raise "Internal error - Unrecognized command #{command.inspect}"
  end

end
